Revert "prplmesh_utils.sh: remove ebtables rule"
This reverts commit 34b84d5481708388f49bef9df1b9e6ae72de22e8.

Without the ebtables rules, some messages were flooded (the 1905
multicast messages most likely) which lead to the connection between
devices to be completely unusable.
When this happened, the following was visible in the system logs:
Fri Oct 29 13:37:54 2021 kern.warn kernel: [12784.463561] br-lan: received packet on wlan0.sta4 with own address as source address (addr:b2:83:c4:0d:f4:ae, vlan:0)

We initially tried to come up with another ebtables rule that would
only drop some of the traffic, but it didn't work.

After a lot of local testing, we found out that keeping the ebtables
rule was not a problem, at least if the devices are started in a
specific order (controller first, then the agents one by one).  With
the ebtables rule enabled again, we were able to connect 5 devices to
the controller were prplMesh was operational on all of them, and the
connection was still stable. Note that due to a mistake when testing,
it was tested with max_num_sta set to 1 (so it's still possible that
the ebtables is in the end still needed when multiple STAs are
connected to the same AP).

diff --git a/common/beerocks/scripts/prplmesh_utils.sh.in b/common/beerocks/scripts/prplmesh_utils.sh.in
--- a/common/beerocks/scripts/prplmesh_utils.sh.in
+++ b/common/beerocks/scripts/prplmesh_utils.sh.in
@@ -113,11 +113,11 @@ prplmesh_platform_db_init() {
 prplmesh_framework_init() {
     # This is required for solveing issue which causing meesges not geeting to their destination.
     # For more information see: https://github.com/prplfoundation/prplMesh/pull/1029#issuecomment-608353274
-#     ebtables -A FORWARD -d 01:80:c2:00:00:13 -j DROP || {
-#         printf "Failed to add the required ebtables rule.\n" >&2
-#         printf "Please make sure the 'ebtables' kernel module is loaded and try again.\n" >&2
-#         exit 1
-#     }
+    ebtables -A FORWARD -d 01:80:c2:00:00:13 -j DROP || {
+        printf "Failed to add the required ebtables rule.\n" >&2
+        printf "Please make sure the 'ebtables' kernel module is loaded and try again.\n" >&2
+        exit 1
+    }
 
     echo "prplmesh_framework_init - starting ieee1905_transport process..."
     "$PRPLMESH_DIR/bin/ieee1905_transport" &
@@ -126,7 +126,7 @@ prplmesh_framework_init() {
 prplmesh_framework_deinit() {
     echo "prplmesh_framework_deinit - killing ieee1905_transport process..."
     killall_program ieee1905_transport
-#     ebtables -D FORWARD -d 01:80:c2:00:00:13 -j DROP
+    ebtables -D FORWARD -d 01:80:c2:00:00:13 -j DROP
 }
 
 prplmesh_controller_start() {
