common: prplmesh_utils.sh: add crashed controller check
Adds check that fixes the problem when in controller mode the controller process is not found, but the 'operational' status is mistakenly returned.

PPM-1634

Signed-off-by: Victor Pushkarev <v.pushkarev@inango-systems.com>
(cherry picked from commit fef5a02fda18bffd11f65484cfadfeef0c1fb34a)
Signed-off-by: Frederik Van Bogaert <frederik.vanbogaert@mind.be>
(cherry picked from commit 42f1fa6198a5a5fa33a1e9de51e00a82a02c3556)
Signed-off-by: Frederik Van Bogaert <frederik.vanbogaert@mind.be>

diff --git a/common/beerocks/scripts/prplmesh_utils.sh.in b/common/beerocks/scripts/prplmesh_utils.sh.in
--- a/common/beerocks/scripts/prplmesh_utils.sh.in
+++ b/common/beerocks/scripts/prplmesh_utils.sh.in
@@ -331,22 +331,34 @@ status_function() {
             exit 1
         fi
     else
+        # Fall if the controller process is not found in controller mode
+        dbg "PRPLMESH_MODE: $PRPLMESH_MODE"
+        case $PRPLMESH_MODE in
+            *"c"* | *"C"*)
+                err "controller process not found"
+                exit 1
+                ;;
+            "a" | "A")
+                dbg "detect MultiAP Agent mode"
+                ;;
+            *)  err "unknown mode"; ;;
+        esac
+
         echo "executing operational test using grep on log files"
-        # check for operational status
+        # Check for operational status
         LOGS_PATH=@BEEROCKS_LOG_FILES_PATH@
 
         error=0
         report "Main agent operational" main_agent_operational $LOGS_PATH
         # For each existing slave log file, check if they are OPERATIONAL:
         main_agent_log="$LOGS_PATH/beerocks_agent@BEEROCKS_LOG_FILES_SUFFIX@"
-        # skip files that aren't symlinks (and skip the literal glob if there is no matching file):
+        # Skip files that aren't symlinks (and skip the literal glob if there is no matching file):
         [ -L "$main_agent_log" ] || return
 
         radios=$(grep 'fronthaul_iface=' "$main_agent_log"  | cut -d "=" -f2)
         for radio in $radios ; do
             report "$radio radio agent operational" radio_agent_operational "$LOGS_PATH" "$radio"
         done
-
         exit $error
     fi
 }
