ci: remove OSP build Trigger external OSP build without pushing the artifacts to prplMesh CI.
Signed-off-by: Maarten De Decker <maarten.dedecker@mind.be>
(cherry picked from commit 0d32000a07e9844eb043e804bec29bc0b5bbcce6)

diff --git a/ci/platform.yml b/ci/platform.yml
--- a/ci/platform.yml
+++ b/ci/platform.yml
@@ -77,62 +77,55 @@ build-for-haze:
   variables:
     TARGET_DEVICE: "haze"
 
-trigger-build-for-osp:
+build-for-osp:
   stage: build
+  variables:
+    POLLING_RATE: "120"
+    TESTS_TO_RUN_R4_ESSENSIUM: ""
+    DEVICE_UNDER_TEST_R4_ESSENSIUM: ""
   script:
     - echo "Triggering OSP runner to start external build"
     - |
-      curl -X POST --retry 3 -s -o /dev/null -F \
-      token=${OSP_PIPELINE_TRIGGER_TOKEN} \
-      -F ref="main-v2.5" \
+      trigger_details=$(curl -X POST --retry 3 -s -f -F \
+      token=${OSP_PIPELINE_TRIGGER_TOKEN_2} \
+      -F ref="main" \
       -F variables[PRPLMESH_REVISION]="$CI_COMMIT_SHA" \
       -F variables[PARENT_PIPELINE_ID]="$CI_PIPELINE_ID" \
       -F variables[PARENT_PROJECT_ID]="$CI_PROJECT_ID" \
       -F variables[MR_TARGET_SHA]="$CI_MERGE_REQUEST_TARGET_BRANCH_SHA" \
       -F variables[MR_SOURCE_SHA]="$CI_MERGE_REQUEST_SOURCE_BRANCH_SHA" \
-      https://gitlab.com/api/v4/projects/42882131/trigger/pipeline
-  needs: []
-  tags:
-    - osp-build-fetch
-
-build-for-osp:
-  stage: build
-  script:
-    - echo "Grabbing the build-for-osp package generated by trigger-build-for-osp"
+      -F variables[TESTS_TO_RUN_R4_ESSENSIUM]="$TESTS_TO_RUN_R4_ESSENSIUM" \
+      -F variables[DEVICE_UNDER_TEST_R4_ESSENSIUM]="$DEVICE_UNDER_TEST_R4_ESSENSIUM" \
+      ${CI_API_V4_URL}/projects/52461766/trigger/pipeline)
+    - if [ $? -ne 0 ] ; then echo "Triggering external runner failed" && exit 1; fi
+    - downstream_pipeline_url=$(echo "$trigger_details" | jq -e -r -c ".web_url")
+    - echo "External builder running at ${downstream_pipeline_url}"
     - mkdir -p "buildWHM"
     - |
       # Checks if package file exists in the OSP package and fills the OSP_PACKAGE_FILE_ID var
       OSP_PACKAGE_FILE_ID=0
       check_package_file () {
           OSP_PACKAGE_FILE_ID=0
-          local package_files=$(curl --fail --show-error --retry 3 -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/${OSP_PACKAGE_ID}/package_files?per_page=100")
+          local package_files=$(curl --fail --show-error --retry 3 -s --header "JOB-TOKEN: ${CI_JOB_TOKEN}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/${OSP_PACKAGE_ID}/package_files?per_page=100")
           OSP_PACKAGE_FILE_ID=$(echo "$package_files" | jq -e -c ".[] | select ( .file_name == \"${1}\") | .id" | sed -n \$p)
       }
       # Wait for successfull build start
       until check_package_file "${CI_PIPELINE_ID}.build_started"
       do
-          sleep 120
+          sleep "$POLLING_RATE"
       done
       echo "Build started on external runner!"
-      # Wait for successfull build artifact upload
-      until check_package_file "${CI_PIPELINE_ID}.tar.gz"
+      # Wait for successfull build
+      until check_package_file "${CI_PIPELINE_ID}.build_success"
       do
           # Check if build failed
           if check_package_file "${CI_PIPELINE_ID}.build_failed" ; then
-              echo "Build FAILED!"
-              exit 1
+              echo "Build FAILED!" && exit 1
           fi
-          sleep 120
+          sleep "$POLLING_RATE"
       done
-    - echo "Found build package in OSP registry, downloading and extracting it!"
-    - 'curl --fail --show-error --retry 3 -s --output build.tar.gz --header "JOB-TOKEN: $CI_JOB_TOKEN" "https://gitlab.com/prpl-foundation/prplmesh/prplMesh/-/package_files/${OSP_PACKAGE_FILE_ID}/download"'
-    - tar --warning=no-timestamp -xvf build.tar.gz
-  artifacts:
-    paths:
-      - "buildWHM/*"
-    expire_in: 1 day
-    when: always
-  needs: ["trigger-build-for-osp"]
+    - echo "OSP build succeeded! Visit pipeline at ${downstream_pipeline_url}"
+  needs: []
   timeout: 3h
   tags:
     - osp-build-fetch
